language: en_us
working_directory: server
start_command: ''
parser: vanilla_parser
encoding:
decoding:
console_command_prefix: '!!'
enable_rcon: false
rcon_address: 127.0.0.1
rcon_port: 25575
rcon_password: password
disable_console_thread: false
download_update: true
debug_mode: false
